[package]
name = "positions-api"
version = "0.1.0"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]

[dependencies]
tokio-core = "^0.1"
futures = "^0.1"
error-chain = "^0.10"
chrono = "^0.4"
log = "0.3"
fern = "^0.4"
serde_json = "^1.0"

[dependencies.hyper]
git = "https://github.com/DevHeap/hyper"

[dependencies.circles-common]
path = "../../lib/circles-common/"
