matrix:
  include:
    - language: rust
      cache: cargo
      rust: nightly
      script:
        - cargo test

    - language: java
      jdk: oraclejdk8
      before_script:
        - cd clientcirclesapi/
      script:
        - mvn test -B