version: '2'
services:
  some-mongo:
    image: "mongo:3"
    volumes:
      - /graylog/data/mongo:/data/db
  some-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.1.1-1
    volumes:
      - /etc/graylog/data/journal:/usr/share/graylog/data/journal
      - /etc/graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: TSFkVUdUORhOtZOLOET0m7Df84AMq1lkk6lIKQURMy7fyNDDVRDnt4X
      GRAYLOG_ROOT_PASSWORD_SHA2: a5624245a182d587ff6109bfaa00edc38cc4bd18603c1d934c200ff3382e62b2
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - some-mongo:mongo
      - some-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"
